### ISSUE TITLE
proxylib_test seg faults when run

### ISSUE THREAD

**Issue by luismolina13** [ferozsalam/FYP#1]
Hey thanks a lot for putting this up. I have been trying to compile the library from their website for my research. But it doesn't seem to work. Yours worked for me....well it compiled but when I run the tests it seg faults. Do you know what might be going on?

Thanks any help is appreciated!

**Comment by ferozsalam** [comment]
Sorry for the late response on this. I'm afraid I don't know what the issue might be - it's been a few years since I last touched this code and I put it out there in the hope that someone else might find it useful and be able to build upon it. I'm sorry I can't be of more help - good luck with it!

**Comment by luismolina13** [comment]
No worries, thanks for the message. It ended up being that something was off with our machine setup. We managed to make it work in the end. Thanks anyways!
